language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
sudo: false
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- gulp
- xvfb-run gulp test:integration
